routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'RootController@index')->name('root');

Route::group(['prefix' => 'uwc', 'namespace' => 'Uwc', 'middleware' => ['auth'], 'as' => 'uwc.'], function () {
    Route::get('/home', 'HomeController@home')->name('home');
    Route::group(['prefix' => 'employees', 'as' => 'employees.'], function () {
        Route::get('/', 'EmployeeController@list')->name('view.list');
        Route::get('create', 'EmployeeController@createView')->name('view.create');
        Route::get('/{id}', 'EmployeeController@edit')->name('view.edit');
        Route::post('/', 'EmployeeController@create')->name('create');
        Route::put('/{id}', 'EmployeeController@update')->name('update');
        Route::delete('/{id}', 'EmployeeController@delete')->name('delete');
    });
    Route::group(['prefix' => 'defects', 'as' => 'defects.'], function () {
        Route::get('/', 'DefectController@list')->name('view.list');
        Route::get('create', 'DefectController@createView')->name('view.create');
        Route::post('/', 'DefectController@createView')->name('create');
    });
    Route::group(['prefix' => 'traceabilities', 'as' => 'stations.'], function () {
        Route::get('/', 'StationController@list')->name('view.list');
    });
    Route::group(['prefix' => 'production-line-analytics', 'as' => 'production-line-analytics.'], function () {
        Route::get('/', 'ProductionLineAnalyticsController@index')->name('view.index');
    });
    Route::group(['prefix' => 'employee-shifts', 'as' => 'employee-shifts.'], function () {
        Route::get('/', 'EmployeeShiftController@list')->name('view.list');
    });
    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/', 'ReportController@index')->name('view.index');
        Route::post('/', 'ReportController@download')->name('download');
    });
});


Route::group(['prefix' => 'covid19-tracking', 'namespace' => 'Covid19', 'middleware' => ['auth'], 'as' => 'covid19.'], function () {
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/users', 'HomeController@userList')->name('users.list');
    Route::get('/user-interactions', 'HomeController@userInteractionList')->name('user-interactions.list');
    Route::get('/infection-tree', 'HomeController@infectionTree')->name('infection-tree');
    Route::get('/news-feed', 'HomeController@newsFeed')->name('news-feed.home');
    Route::get('/hotspot-map', 'HomeController@hotspotMap')->name('hotspot-map.home');
    Route::get('/notification', 'HomeController@notificationList')->name('notification.list');
});

app/Models/Uwc/Defect.php
<?php

namespace App\Models\Uwc;

use Illuminate\Database\Eloquent\Model;

class Defect extends Model
{
    protected $connection = 'uwc';

    public $table = 'defects';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'employee_id',
        'production_line_no',
        'station_no',
        'object_type',
        'traceability_no',
        'units',
        'pfr_no',
        'reason',
        'batch_id'
    ];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('D, M d, Y');
    }
}

app/Http/Controllers/Uwc/DefectController.php
<?php

namespace App\Http\Controllers\Uwc;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Uwc\Defect;

class DefectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function list(Request $request)
    {
        session(['active_nav' => 'defects']);

        return view('uwc.layouts.defects.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createView(Request $request)
    {
        session(['active_nav' => 'defects']);

        return view('uwc.layouts.defects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/uwc/layouts/defects/create.blade.php
@extends('uwc.master')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-4">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Add Defective Unit</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('uwc.home') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('uwc.employees.view.list') }}">Defect Management</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card card-success">
                        <form method="POST" action="{{ route('uwc.defects.create') }}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="employee_id">Employee ID</label>
                                    <input type="text" class="form-control @error('employee_id') is-invalid @enderror" id="employee_id" name="employee_id" placeholder="E.g. 0123">
                                    @error('employee_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="name">Full Name</label>
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="E.g. John Doe">
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="contact_no">Contact No</label>
                                    <input type="text" class="form-control @error('contact_no') is-invalid @enderror" id="contact_no" name="contact_no" placeholder="E.g. 011-12345678">
                                    @error('contact_no')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-success"><i class="fas fa-save pr-2"></i>Save</button>
                                <a href="{{ route('uwc.employees.view.list') }}" class="btn btn-dark"><i class="fas fa-times pr-2"></i>Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/uwc/layouts/defects/list.blade.php
@extends('uwc.master')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-4">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Defects</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('uwc.home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Defects</li>
                    </ol>
                </div>
            </div>

            {{-- Search and Filter --}}
            <div class="row">
                <div class="col-md-2 col-6">
                    <label for="production_line_dropdown">Production Line:</label>
                    <div class="form-group">
                        <select class="form-control select2bs4 select2bs4-success" data-dropdown-css-class="select2-success"
                            name="production_line" id="production_line" style="width: 100% !important;">
                            <option value="all">All</option>
                            @for ($i = 1; $i <= config('staticdata.production_line_limit'); $i++)
                                <option value="{{ $i }}">{{ $i }}</option>
                            @endfor
                        </select>
                    </div>
                </div>
                <div class="col-md-1 col-6">
                    <label for="station">Station:</label>
                    <div class="form-group">
                        <select class="form-control select2bs4 select2bs4-success" data-dropdown-css-class="select2-success"
                            name="station" id="station" style="width: 100% !important;">
                            <option value="all">All</option>
                            @for ($i = 1; $i <= 3; $i++)
                                <option value="{{ $i }}">{{ $i }}</option>
                            @endfor
                        </select>
                    </div>
                </div>
                <div class="col-md-2 col-6">
                    <label for="start_date_range">Date From:</label>
                    <div class="form-group">
                        <input name="start_date_range" id="start_date_range">
                    </div>
                </div>
                <div class="col-md-2 col-6">
                    <label for="end_date_range">Date To:</label>
                    <div class="form-group">
                        <input name="end_date_range" id="end_date_range">
                    </div>
                </div>
                <div class="col-md-4 col-12">
                    <label for="search_dropdown">Search By:</label>
                    <div class="input-group">
                        <select class="custom-select select2bs4 select2bs4-success" data-dropdown-css-class="select2-success"
                            name="search_dropdown" id="search_dropdown" style="width: 50%">
                        <option value="" selected disabled>Select Category</option>
                        @foreach (config('staticdata.defects.search-dropdown') as $key => $value)
                            <option value="{{ $key }}">{{ $value }}</option>
                        @endforeach
                        </select>

                        <input type="text" id="keyword" class="form-control" placeholder="Search keyword.." disabled
                            aria-label="Search keyword.." aria-describedby="basic-addon2" style="border-radius: 0%;">

                        <div class="input-group-append">
                            <button class="btn btn-success" id="search_btn" type="button" disabled><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
                <div class="col-xl-1 col-md-2 col-12">
                    <div class="web-view mt-md-4 pt-md-2 mt-3 pt-2"></div>
                    <div class="form-group">
                        <button class="btn btn-success w-100" id="reset_filter_btn" type="button"><i class="fas fa-undo pr-2"></i>Reset</button>
                    </div>
                </div>
            </div>

            {{-- Table --}}
            <div class="row">
                <div class="col-12">
                    <div class="card card-success">
                        <div class="card-header text-white bg-success">
                            <h3 class="card-title">Defects Table</h3>
                        </div>
                        <div class="card-body">
                            <input type="hidden" id="datatable_api_route" value="{{ route('uwc.api.defects.datatable.list') }}">
                            <table id="defect_table" class="table table-bordered table-striped table-hover w-100">
                                <thead>
                                    <tr>
                                        <th>PFR</th>
                                        <th>Production Line</th>
                                        <th>Station</th>
                                        <th>Type</th>
                                        <th>Traceability</th>
                                        <th>Qty</th>
                                        <th>Reported At</th>
                                        <th>Reported By</th>
                                        <th>Reason</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(function() {
    const options = { year: 'numeric', month: 'long', day: '2-digit' };
    const default_start_date = 'January 01, <?php echo \Carbon\Carbon::now()->year ?>';
    const default_end_date = new Date().toLocaleDateString("en-US", options);

    $('.select2bs4').select2();
    $(".select2-selection").eq(2).css({"border-top-right-radius": "0%", "border-bottom-right-radius": "0%"});

    $('#start_date_range').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'mmmm dd, yyyy',
        value: default_start_date
    });

    $('#end_date_range').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'mmmm dd, yyyy',
        value: default_end_date
    });

    var defect_table = $('#defect_table').DataTable({
        "lengthChange": false,
        "searching": false,
        "pageLength": 10,
        "processing": true,
        "serverSide": true,
        "scrollX": true,
        "order": [[ 6, "desc" ]],
        "ajax": {
            "url": $("#datatable_api_route").val(),
            "data": function ( data ) {
                data.production_line_no = $("#production_line").val()
                data.station_no = $("#station").val();
                data.start_date = $("#start_date_range").val();
                data.end_date = $("#end_date_range").val();
                data.search_by = $("#search_dropdown").val();
                data.keyword = $("#keyword").val();
            }
        },
        "columns": [
            { data: 'pfr_no' },
            { data: 'production_line_no' },
            { data: 'station_no' },
            { data: 'object_type' },
            { data: 'traceability_no' },
            { data: 'units' },
            { data: 'created_at' },
            { data: 'employee_id' },
            { data: 'reason' }
        ]
    });

    $('a[data-widget="pushmenu"]').on( 'click', function (e) {
        setTimeout(function(){
            $.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
        }, 300);
    });

    $("#search_btn").on('click', function () {
        defect_table.search( this.value ).draw();
    })

    $("#reset_filter_btn").on('click', function () {
        $("#start_date_range").val(default_start_date);
        $("#end_date_range").val(default_end_date);
        $("#search_dropdown").val('');
        $("#search_dropdown").change();
        $("#keyword").val('');
        defect_table.search( this.value ).draw();
    })
    
    $('#production_line').on('change', function(e) {
        defect_table.draw();
    });
    
    $('#station').on('change', function(e) {
        defect_table.draw();
    });
    
    $('#keyword').on('keyup', function(e) {
        if (e.which == 13) {
            $("#search_btn").click();
        }
        
        if ($(this).val().length == 0) {
            $("#search_btn").prop('disabled', true);
        } else {
            $("#search_btn").prop('disabled', false);
        }
    });

    $('#search_dropdown').on('change', function(e) {
        if (!$(this).val()) {
            $("#keyword").prop('disabled', true);
        } else {
            $("#keyword").prop('disabled', false);
        }
    });  
})

</script>
@endsection