routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'RootController@index')->name('root');

Route::group(['prefix' => 'uwc', 'namespace' => 'Uwc', 'middleware' => ['auth'], 'as' => 'uwc.'], function () {
    Route::get('/home', 'HomeController@home')->name('home');
    Route::group(['prefix' => 'employees', 'as' => 'employees.'], function () {
        Route::get('/', 'EmployeeController@list')->name('view.list');
        Route::get('create', 'EmployeeController@createView')->name('view.create');
        Route::get('/{id}', 'EmployeeController@edit')->name('view.edit');
        Route::post('/', 'EmployeeController@create')->name('create');
        Route::put('/{id}', 'EmployeeController@update')->name('update');
        Route::delete('/{id}', 'EmployeeController@delete')->name('delete');
    });
    Route::group(['prefix' => 'defects', 'as' => 'defects.'], function () {
        Route::get('/', 'DefectController@list')->name('view.list');
        Route::get('create', 'DefectController@createView')->name('view.create');
        Route::post('/', 'DefectController@createView')->name('create');
    });
    Route::group(['prefix' => 'traceabilities', 'as' => 'stations.'], function () {
        Route::get('/', 'StationController@list')->name('view.list');
    });
    Route::group(['prefix' => 'production-line-analytics', 'as' => 'production-line-analytics.'], function () {
        Route::get('/', 'ProductionLineAnalyticsController@index')->name('view.index');
    });
    Route::group(['prefix' => 'employee-shifts', 'as' => 'employee-shifts.'], function () {
        Route::get('/', 'EmployeeShiftController@list')->name('view.list');
    });
    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/', 'ReportController@index')->name('view.index');
        Route::post('/', 'ReportController@download')->name('download');
    });
});


Route::group(['prefix' => 'covid19-tracking', 'namespace' => 'Covid19', 'middleware' => ['auth'], 'as' => 'covid19.'], function () {
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/users', 'HomeController@userList')->name('users.list');
    Route::get('/user-interactions', 'HomeController@userInteractionList')->name('user-interactions.list');
    Route::get('/infection-tree', 'HomeController@infectionTree')->name('infection-tree');
    Route::get('/news-feed', 'HomeController@newsFeed')->name('news-feed.home');
    Route::get('/hotspot-map', 'HomeController@hotspotMap')->name('hotspot-map.home');
    Route::get('/notification', 'HomeController@notificationList')->name('notification.list');
});

app/Models/Uwc/Employee.php
<?php

namespace App\Models\Uwc;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;

    protected $connection = 'uwc';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'employee_id', 'name', 'card_no'
    ];
}

app/Http/Controllers/Uwc/Api/ChartApiController.php
<?php

namespace App\Http\Controllers\Uwc\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Uwc\AnalyticsService;

class ChartApiController extends Controller
{
    private $analytics_service;

    public function __construct()
    {
        $this->analytics_service = new AnalyticsService;
    }

    public function getDailyPercentageChartData(Request $request)
    {
        $data = $this->analytics_service->getDailyPercentage($request->production_line);
        
        return response()->json(
            [
                'message' => 'success',
                'attributes' => [
                    'working_hours' => $data['working_hours'],
                    'total_units' => $data['total_units'],
                    'total_avg_units_per_hour' => $data['total_avg_units_per_hour'],
                    'defects_percentage' => $data['defects_percentage'],
                    'avg_units_per_hour' => config('staticdata.avg_units_per_hour'),
                    'total_production_line' => config('staticdata.production_line_limit'),
                    'total_station' => config('staticdata.station_limit')
                ]
            ],
            200
        );
    }

    public function getUnitsCompletedChartData(Request $request)
    {
        $data = $this->analytics_service->getUnitsCompleted($request->production_line, $request->filter);

        return response()->json(
            [
                'message' => 'success',
                'attributes' => [
                    'year' => $data['year'],
                    'title' => $data['title'],
                    'subtitle' => $data['subtitle'],
                    'x_axis' => $data['x_axis'],
                    'station1' => $data['station1'],
                    'station2' => $data['station2'],
                    'station3' => $data['station3'],
                    'is_1_month' => $data['is_1_month'] ?? false,
                    'month_year' => $data['month_year'] ?? null
                ]
            ],
            200
        );
    }

    public function getDefectiveUnitsChartData(Request $request)
    {
        $data = $this->analytics_service->getDefectiveUnits($request->production_line, $request->filter);

        return response()->json(
            [
                'message' => 'success',
                'attributes' => [
                    'year' => $data['year'],
                    'title' => $data['title'],
                    'subtitle' => $data['subtitle'],
                    'x_axis' => $data['x_axis'],
                    'defects' => $data['defects'],
                    'is_1_month' => $data['is_1_month'] ?? false,
                    'month_year' => $data['month_year'] ?? null
                    ]
                ],
                200
            );
    }
}

app/Http/Controllers/Uwc/Api/DefectApiController.php
<?php

namespace App\Http\Controllers\Uwc\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Uwc\Defect;
use Carbon\Carbon;

class DefectApiController extends Controller
{
    public function datatableList(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get('start');
        $length = $request->get('length');

        if ($draw == 1) {
            $sort = 'created_at';
            $order = 'desc';
        } else {
            $sort = config('staticdata.defects.table-header.' . $request['order'][0]['column']);
            $request['order'][0]['dir'] == 'asc' ? $order = 'asc' : $order = 'desc';
        }

        $request->start_date ? $request->start_date = Carbon::parse($request->start_date)->format('Y-m-d H:i:s') : null;
        $request->end_date ? $request->end_date = Carbon::parse($request->end_date)->addDay()->subSecond(1)->format('Y-m-d H:i:s') : null;

        $total = Defect::when($request->production_line_no != 'all', function($q) use ($request) {
                return $q->where('production_line_no', $request->production_line_no);
            })
            ->when($request->station_no != 'all', function($q) use ($request) {
                return $q->where('station_no', $request->station_no);
            })
            ->when($request->start_date && $request->end_date, function($q) use ($request) {
                return $q->whereBetween('created_at', [$request->start_date, $request->end_date]);
            })
            ->when($request->search_by, function($q) use ($request) {
                return $q->whereRaw("$request->search_by LIKE '%". strtoupper($request->keyword) . "%'");
            })->count();
            
        $defect_list = Defect::select(
            'pfr_no',
            'production_line_no',
            'station_no',
            'object_type',
            'traceability_no',
            'employee_id',
            'created_at',
            'units',
            'reason')
            ->when($request->production_line_no != 'all', function($q) use ($request) {
                return $q->where('production_line_no', $request->production_line_no);
            })
            ->when($request->station_no != 'all', function($q) use ($request) {
                return $q->where('station_no', $request->station_no);
            })
            ->when($request->start_date && $request->end_date, function($q) use ($request) {
                return $q->whereBetween('created_at', [$request->start_date, $request->end_date]);
            })
            ->when($request->search_by, function($q) use ($request) {
                return $q->whereRaw("$request->search_by LIKE '%". strtoupper($request->keyword) . "%'");
            })
            ->orderBy($sort, $order)
            ->offset($start)
            ->limit($length)
            ->get();

        foreach ($defect_list as $defect) {
            // $defect->created_at = Carbon::createFromFormat('Y-m-d H:i:s', $defect->created_at)->format('Y-m-d');
            $defect->object_type = ucfirst($defect->object_type);
            if (strlen($defect->traceability_no) > 20) {
                $defect->traceability_no = substr_replace($defect->traceability_no, '-<br>', 19, 0);
            }
        }

        $data = [
            'draw' => $draw,
            'recordsTotal' => $total,
            'recordsFiltered' => $total,
            'data' => $defect_list,
        ];

        echo json_encode($data, JSON_PRETTY_PRINT);
    }
}

app/Http/Controllers/Uwc/Api/EmployeeManagementApiController.php
<?php

namespace App\Http\Controllers\Uwc\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Uwc\Employee;
use App\Services\Uwc\EmployeeService;
use Carbon\Carbon;

class EmployeeManagementApiController extends Controller
{
    private $employee_service;

    public function __construct()
    {
        $this->employee_service = new EmployeeService;
    }

    public function datatableList(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get('start');
        $length = $request->get('length');

        if ($draw == 1 || $request['order'][0]['column'] == 3) {
            $sort = 'created_at';
            $order = 'desc';
        } else {
            $sort = config('staticdata.employees.table-header.' . $request['order'][0]['column']);
            $request['order'][0]['dir'] == 'asc' ? $order = 'asc' : $order = 'desc';
        }

        $total = Employee::when($request->search_by, function($q) use ($request) {
            return $q->whereRaw("$request->search_by LIKE '%". strtoupper($request->keyword) . "%'");
        })->count();

        $employee_list = Employee::select(
            'id',
            'employee_id',
            'name',
            'card_no')
            ->when($request->search_by, function($q) use ($request) {
                return $q->whereRaw("$request->search_by LIKE '%". strtoupper($request->keyword) . "%'");
            })
            ->orderBy($sort, $order)
            ->offset($start)
            ->limit($length)
            ->get();

        foreach ($employee_list as $employee) {
            $employee->total_working_hours = $this->employee_service->formatInHours($this->employee_service->getTotalWorkingHours($employee->employee_id));
            if ($request->is_admin) {
                $employee->delete = '<a class="delete-icon" href="#delete_modal" data-toggle="modal" data-target="#delete_modal" ' .
                                        'data-employee_id="' . $employee->employee_id . '">' .
                                        '<i class="fas fa-trash-alt"></i>' .
                                    '</a>';
                $employee->employee_id = '<a href="' . route("uwc.employees.view.edit", ["id" => $employee->id]) . '">' .
                                            $employee->employee_id .
                                         '</a>';
            }
        }

        $employee_list = $employee_list->toArray();

        // if ($request['order'][0]['column'] == 3) {
        //     usort($employee_list, function($a, $b) use ($request) {
        //         if ($request['order'][0]['dir'] == 'asc') {
        //             return $a['total_working_hours'] - $b['total_working_hours'];
        //         } else {
        //             return $b['total_working_hours'] - $a['total_working_hours'];
        //         }
        //     });
        // }

        $data = [
            'draw' => $draw,
            'recordsTotal' => $total,
            'recordsFiltered' => $total,
            'data' => $employee_list,
        ];

        echo json_encode($data, JSON_PRETTY_PRINT);
    }
}

app/Http/Controllers/Uwc/Api/EmployeeShiftApiController.php
<?php

namespace App\Http\Controllers\Uwc\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Uwc\EmployeeShift;
use App\Models\Uwc\Employee;
use Carbon\Carbon;

class EmployeeShiftApiController extends Controller
{
    public function datatableList(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get('start');
        $length = $request->get('length');

        if ($draw == 1) {
            $sort = 'clock_in_datetime';
            $order = 'desc';
        } else {
            $sort = config('staticdata.employee_shifts.table-header.' . $request['order'][0]['column']);
            $request['order'][0]['dir'] == 'asc' ? $order = 'asc' : $order = 'desc';
        }

        $request->start_date ? $request->start_date = Carbon::parse($request->start_date)->format('Y-m-d H:i:s') : null;
        $request->end_date ? $request->end_date = Carbon::parse($request->end_date)->addDay()->subSecond(1)->format('Y-m-d H:i:s') : null;

        $total = EmployeeShift::when($request->production_line_no != 'all', function($q) use ($request) {
                return $q->where('production_line_no', $request->production_line_no);
            })
            ->when($request->station_no != 'all', function($q) use ($request) {
                return $q->where('station_no', $request->station_no);
            })
            ->where('clock_out_datetime', '!=', 'NULL')
            ->when($request->start_date && $request->end_date, function($q) use ($request) {
                return $q->whereBetween('clock_out_datetime', [$request->start_date, $request->end_date]);
            })
            ->when($request->search_by, function($q) use ($request) {
                return $q->whereRaw("$request->search_by LIKE '%". strtoupper($request->keyword) . "%'");
            })->count();

        $shift_list = EmployeeShift::select(
            'employee_id',
            'pfr_no',
            'production_line_no',
            'station_no',
            'clock_in_datetime',
            'clock_out_datetime',
            'working_hours')
            ->when($request->production_line_no != 'all', function($q) use ($request) {
                return $q->where('production_line_no', $request->production_line_no);
            })
            ->when($request->station_no != 'all', function($q) use ($request) {
                return $q->where('station_no', $request->station_no);
            })
            ->where('clock_out_datetime', '!=', 'NULL')
            ->when($request->start_date && $request->end_date, function($q) use ($request) {
                return $q->whereBetween('clock_out_datetime', [$request->start_date, $request->end_date]);
            })
            ->when($request->search_by, function($q) use ($request) {
                return $q->whereRaw("$request->search_by LIKE '%". strtoupper($request->keyword) . "%'");
            })
            ->orderBy($sort, $order)
            ->offset($start)
            ->limit($length)
            ->get();

        foreach ($shift_list as $shift) {
            $shift->clock_in_datetime = Carbon::parse($shift->clock_in_datetime)->toDayDateTimeString();
            $shift->clock_out_datetime = Carbon::parse($shift->clock_out_datetime)->toDayDateTimeString();
            $shift->working_hours = number_format($shift->working_hours / 60, 2, '.', ',');
        }

        $data = [
            'draw' => $draw,
            'recordsTotal' => $total,
            'recordsFiltered' => $total,
            'data' => $shift_list,
        ];

        echo json_encode($data, JSON_PRETTY_PRINT);
    }
}

app/Http/Controllers/Uwc/EmployeeShiftController.php
<?php

namespace App\Http\Controllers\Uwc;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class EmployeeShiftController extends Controller
{
    public function list()
    {
        session(['active_nav' => 'employee-shifts']);

        return view('uwc.layouts.employee-shifts.list');
    }
}

app/Http/Controllers/Uwc/HomeController.php
<?php

namespace App\Http\Controllers\Uwc;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\Uwc\AnalyticsService;

class HomeController extends Controller
{
    private $analytics_service;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->analytics_service = new AnalyticsService;
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function home()
    {
        session(['active_nav' => 'dashboard']);
        
        return view('uwc.layouts.dashboard');
    }
}

resources/views/uwc/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; {{ \Carbon\Carbon::now()->year }} <a target="_blank" href="https://cedartech.com.my">Cedar Technologies</a>.</strong> All rights reserved.
</footer>

resources/views/uwc/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-success">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        {{-- <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('home') }}" class="nav-link">Home</a>
        </li> --}}
    </ul>

    <!-- SEARCH FORM -->
    <!-- <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
            </button>
            </div>
        </div>
    </form> -->

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <!-- <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <div class="media">
                        <img src="/img/avatar-blank.png" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <div class="media">
                        <img src="/img/avatar-blank.png" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <div class="media">
                        <img src="/img/avatar-blank.png" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li> -->
        <!-- Notifications Dropdown Menu -->
        <!-- <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
                <i class="fas fa-envelope mr-2"></i> 4 new messages
                <span class="float-right text-muted text-sm">3 mins</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
                <i class="fas fa-users mr-2"></i> 8 friend requests
                <span class="float-right text-muted text-sm">12 hours</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
                <i class="fas fa-file mr-2"></i> 3 new reports
                <span class="float-right text-muted text-sm">2 days</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li> -->
        <li class="nav-item">
            <!-- <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ route('logout') }}">
                <i class="fas fa-sign-out-alt"></i>
                Logout
            </a> -->
            
            <a class="nav-link" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                <i class="fa fa-fw fa-power-off"></i> Log Out
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/uwc/master.blade.php
<!DOCTYPE html>
<html lang="en" class="gr__adminlte_io">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>UWC</title>

    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <script src="{{ asset('js/app.js') }}"></script>
    
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        @include('uwc.header')

        @include('uwc.sidebar')

        <section class="content">
            @yield('content')
        </section>

        @include('uwc.footer')
    </div>
</body>
</html>

resources/views/uwc/sidebar.blade.php
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-light-success elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('uwc.home') }}" class="brand-link">
      <img src="/img/cedar-logo.png" alt="Cedar Technologies Logo" class="brand-image">
      <span class="brand-text font-weight-light">UWC</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/img/avatar-blank.png" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('uwc.home') }}" class="nav-link {{ session('active_nav') == 'dashboard' ? 'active' : null }}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('uwc.employees.view.list') }}" class="nav-link {{ session('active_nav') == 'employees' ? 'active' : null }}">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Employee Management
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('uwc.employee-shifts.view.list') }}" class="nav-link {{ session('active_nav') == 'employee-shifts' ? 'active' : null }}">
              <i class="nav-icon fas fa-user-check"></i>
              <p>
                Employee Shifts
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('uwc.production-line-analytics.view.index') }}" class="nav-link {{ session('active_nav') == 'production-line-analytics' ? 'active' : null }}">
              <i class="nav-icon fas fa-chart-line"></i>
              <p>
                Production Line Analytics
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('uwc.defects.view.list') }}" class="nav-link {{ session('active_nav') == 'defects' ? 'active' : null }}">
              <i class="nav-icon fas fa-trash"></i>
              <p>
                Defects
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('uwc.stations.view.list') }}" class="nav-link {{ session('active_nav') == 'traceabilities' ? 'active' : null }}">
              <i class="nav-icon fas fa-briefcase"></i>
              <p>
                Traceabilities
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('uwc.reports.view.index') }}" class="nav-link {{ session('active_nav') == 'reports' ? 'active' : null }}">
              <i class="nav-icon fas fa-file-alt"></i>
              <p>
                Generate Report
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>