routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'RootController@index')->name('root');

Route::group(['prefix' => 'uwc', 'namespace' => 'Uwc', 'middleware' => ['auth'], 'as' => 'uwc.'], function () {
    Route::get('/home', 'HomeController@home')->name('home');
    Route::group(['prefix' => 'employees', 'as' => 'employees.'], function () {
        Route::get('/', 'EmployeeController@list')->name('view.list');
        Route::get('create', 'EmployeeController@createView')->name('view.create');
        Route::get('/{id}', 'EmployeeController@edit')->name('view.edit');
        Route::post('/', 'EmployeeController@create')->name('create');
        Route::put('/{id}', 'EmployeeController@update')->name('update');
        Route::delete('/{id}', 'EmployeeController@delete')->name('delete');
    });
    Route::group(['prefix' => 'defects', 'as' => 'defects.'], function () {
        Route::get('/', 'DefectController@list')->name('view.list');
        Route::get('create', 'DefectController@createView')->name('view.create');
        Route::post('/', 'DefectController@createView')->name('create');
    });
    Route::group(['prefix' => 'traceabilities', 'as' => 'stations.'], function () {
        Route::get('/', 'StationController@list')->name('view.list');
    });
    Route::group(['prefix' => 'production-line-analytics', 'as' => 'production-line-analytics.'], function () {
        Route::get('/', 'ProductionLineAnalyticsController@index')->name('view.index');
    });
    Route::group(['prefix' => 'employee-shifts', 'as' => 'employee-shifts.'], function () {
        Route::get('/', 'EmployeeShiftController@list')->name('view.list');
    });
    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/', 'ReportController@index')->name('view.index');
        Route::post('/', 'ReportController@download')->name('download');
    });
});


Route::group(['prefix' => 'covid19-tracking', 'namespace' => 'Covid19', 'middleware' => ['auth'], 'as' => 'covid19.'], function () {
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/users', 'HomeController@userList')->name('users.list');
    Route::get('/user-interactions', 'HomeController@userInteractionList')->name('user-interactions.list');
    Route::get('/infection-tree', 'HomeController@infectionTree')->name('infection-tree');
    Route::get('/news-feed', 'HomeController@newsFeed')->name('news-feed.home');
    Route::get('/hotspot-map', 'HomeController@hotspotMap')->name('hotspot-map.home');
    Route::get('/notification', 'HomeController@notificationList')->name('notification.list');
});

app/Models/Covid19/Interaction.php
<?php

namespace App\Models\Covid19;

use Illuminate\Database\Eloquent\Model;

class Interaction extends Model
{
    protected $connection = 'covid19';

    public $timestamps = false;

    protected $fillable = [
        'mobile_no_1',
        'mobile_no_2',
        'longitude',
        'latitude',
        'distance',
        'interaction_started_at',
        'interaction_ended_at'
    ];

    protected $casts = [
        'interaction_started_at'  => 'date:l, F d, Y H:i:s',
    ];
}

app/Models/Covid19/Location.php
<?php

namespace App\Models\Covid19;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $connection = 'covid19';

    public $timestamps = false;

    protected $fillable = [
        'mobile_no',
        'longitude',
        'latitude',
        'sublocation',
        'timestamps',
    ];
}

app/Models/Covid19/User.php
<?php

namespace App\Models\Covid19;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class User extends Model
{
    protected $connection = 'covid19';

    protected $fillable = [
        'mobile_no',
        'is_doctor',
        'is_government',
        'is_covid_positive',
        'declared_covid_positive_at',
        'notify'
    ];
    
    protected $casts = [
        'declared_covid_positive_at'  => 'date:l, F d, Y H:i:s',
    ];
}

app/Http/Controllers/Covid19/Api/ChartApiController.php
<?php

namespace App\Http\Controllers\Covid19\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Covid19\AnalyticsService;

class ChartApiController extends Controller
{
    private $analytics_service;

    public function __construct()
    {
        $this->analytics_service = new AnalyticsService;
    }

    public function getInfectedUsersChartData(Request $request)
    {
        $data = $this->analytics_service->getInfectedUsers($request->filter);
        
        return response()->json(
            [
                'message' => 'success',
                'attributes' => [
                    'year' => $data['year'],
                    'title' => $data['title'],
                    'subtitle' => $data['subtitle'],
                    'x_axis' => $data['x_axis'],
                    'infected_users' => $data['infected_users'],
                    'is_1_month' => $data['is_1_month'] ?? false,
                    'month_year' => $data['month_year'] ?? null
                ]
            ],
            200
        );
    }

}

app/Http/Controllers/Covid19/Api/InteractionApiController.php
<?php

namespace App\Http\Controllers\Covid19\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Covid19\InteractionService;
use Carbon\Carbon;

class InteractionApiController extends Controller
{
    private $interaction_service;

    public function __construct()
    {
        $this->interaction_service = new InteractionService;
    }

    public function datatableList(Request $request)
    {
        $data = $this->interaction_service->datatableList($request);

        echo $data;
    }
}

app/Http/Controllers/Covid19/Api/NotificationApiController.php
<?php

namespace App\Http\Controllers\Covid19\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Covid19\UserService;
use Carbon\Carbon;

class NotificationApiController extends Controller
{
    private $user_service;

    public function __construct()
    {
        $this->user_service = new UserService;
    }

    public function datatableList(Request $request)
    {
        $data = $this->user_service->notificationDatatableList($request);

        echo $data;
    }

    public function updateInteractedUserNotifyFlag(Request $request)
    {
        $data = $this->user_service->updateInteractedUserNotifyFlag($request);

        return response()->json($data, 200);
    }
}

app/Http/Controllers/Covid19/Api/StatisticApiController.php
<?php

namespace App\Http\Controllers\Covid19\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Covid19\AnalyticsService;

class StatisticApiController extends Controller
{
    private $analytics_service;

    public function __construct()
    {
        $this->analytics_service = new AnalyticsService;
    }

    public function getHeaderData()
    {
        $data = $this->analytics_service->getHeaderData();
        
        return response()->json(
            [
                'message' => 'success',
                'attributes' => $data
            ],
            200
        );
    }

    public function getUnitsCompletedChartData(Request $request)
    {
        $data = $this->analytics_service->getUnitsCompleted($request->production_line, $request->filter);

        return response()->json(
            [
                'message' => 'success',
                'attributes' => [
                    'year' => $data['year'],
                    'title' => $data['title'],
                    'subtitle' => $data['subtitle'],
                    'x_axis' => $data['x_axis'],
                    'station1' => $data['station1'],
                    'station2' => $data['station2'],
                    'station3' => $data['station3'],
                    'is_1_month' => $data['is_1_month'] ?? false,
                    'month_year' => $data['month_year'] ?? null
                ]
            ],
            200
        );
    }

    public function getDefectiveUnitsChartData(Request $request)
    {
        $data = $this->analytics_service->getDefectiveUnits($request->production_line, $request->filter);

        return response()->json(
            [
                'message' => 'success',
                'attributes' => [
                    'year' => $data['year'],
                    'title' => $data['title'],
                    'subtitle' => $data['subtitle'],
                    'x_axis' => $data['x_axis'],
                    'defects' => $data['defects'],
                    'is_1_month' => $data['is_1_month'] ?? false,
                    'month_year' => $data['month_year'] ?? null
                    ]
                ],
                200
            );
    }
}

app/Http/Controllers/Covid19/Api/UserApiController.php
<?php

namespace App\Http\Controllers\Covid19\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\Covid19\UserService;
use Carbon\Carbon;

class UserApiController extends Controller
{
    private $user_service;

    public function __construct()
    {
        $this->user_service = new UserService;
    }

    public function datatableList(Request $request)
    {
        $data = $this->user_service->datatableList($request);

        echo $data;
    }

    public function getInfectionTreeData(Request $request)
    {
        $data = $this->user_service->getInfectionTreeData($request);

        echo $data;
    }

    public function update(Request $request, $id)
    {
        $data = $this->user_service->update($request, $id);

        return response()->json($data, 200);
    }
}

app/Http/Controllers/Covid19/HomeController.php
<?php

namespace App\Http\Controllers\Covid19;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function home()
    {
        session(['active_nav' => 'dashboard']);

        return view('covid19.layouts.dashboard');
    }

    public function userList()
    {
        session(['active_nav' => 'users']);

        return view('covid19.layouts.users-list');
    }

    public function userInteractionList(Request $request)
    {
        session(['active_nav' => 'user-interactions']);
        $notification_mobile_no = $request->mobile_no;

        return view('covid19.layouts.user-interactions-list', compact('notification_mobile_no'));
    }

    public function infectionTree()
    {
        session(['active_nav' => 'infection-tree']);

        return view('covid19.layouts.infection-tree');
    }

    public function newsFeed()
    {
        session(['active_nav' => 'news-feed']);

        return view('covid19.layouts.news-feed');
    }

    public function hotspotMap()
    {
        session(['active_nav' => 'hotspot-map']);

        return view('covid19.layouts.hotspot-map');
    }

    public function notificationList()
    {
        session(['active_nav' => 'notification-list']);

        return view('covid19.layouts.notification-list');
    }
}

resources/views/covid19/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; {{ \Carbon\Carbon::now()->year }} <a target="_blank" href="https://cedartech.com.my">Cedar Technologies</a>.</strong> All rights reserved.
</footer>

resources/views/covid19/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-success">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <!-- <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{{ route('logout') }}">
                <i class="fas fa-sign-out-alt"></i>
                Logout
            </a> -->
            
            <a class="nav-link" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                <i class="fa fa-fw fa-power-off"></i> Log Out
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/covid19/master.blade.php
<!DOCTYPE html>
<html lang="en" class="gr__adminlte_io">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>COVID-19 Tracking</title>
    <script src="https://kit.fontawesome.com/7f357bb1b5.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <script src="{{ asset('js/app.js') }}"></script>
    
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div class="wrapper">
        @include('covid19.header')

        @include('covid19.sidebar') 

        <section class="content">
            @yield('content')
        </section>

        @include('covid19.footer')
    </div>
</body>
</html>

resources/views/covid19/sidebar.blade.php
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-light-success elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('covid19.home') }}" class="brand-link">
      <img src="/img/cedar-logo.png" alt="Cedar Technologies Logo" class="brand-image">
      <span class="brand-text font-weight-light">COVID-19 Tracking</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/img/avatar-blank.png" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('covid19.home') }}" class="nav-link {{ session('active_nav') == 'dashboard' ? 'active' : null }}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('covid19.users.list') }}" class="nav-link {{ session('active_nav') == 'users' ? 'active' : null }}">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Users
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('covid19.user-interactions.list') }}" class="nav-link {{ session('active_nav') == 'user-interactions' ? 'active' : null }}">
              <i class="nav-icon fas fa-people-arrows"></i>
              <p>
                User Interactions
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('covid19.infection-tree') }}" class="nav-link {{ session('active_nav') == 'infection-tree' ? 'active' : null }}">
              <i class="nav-icon fas fa-tree"></i>
              <p>
                Infection Tree
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('covid19.news-feed.home') }}" class="nav-link {{ session('active_nav') == 'news-feed' ? 'active' : null }}">
              <i class="nav-icon fas fa-newspaper"></i>
              <p>
                News Feed
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('covid19.hotspot-map.home') }}" class="nav-link {{ session('active_nav') == 'hotspot-map' ? 'active' : null }}">
              <i class="nav-icon fas fa-globe-asia"></i>
              <p>
                Hotspot Map
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('covid19.notification.list') }}" class="nav-link {{ session('active_nav') == 'notification-list' ? 'active' : null }}">
              <i class="nav-icon fas fa-user-friends"></i>
              <p>
                Contact Tracing
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>